### ISSUE TITLE
`auto release` releases wrong version in lerna monorepo

### ISSUE THREAD

**Issue by nicmosc** [intuit/auto#596] opened 2019-10-08 09:24 UTC
**Describe the bug**

I'm working on a monorepo with lerna, and followed the set up as described in the [doc](https://intuit.github.io/auto/pages/getting-started.html#enabling-skip-release-label). I noticed that after the `lerna publish` command is finished, and tags are pushed, the `auto release` command creates a new (wrong) tag and releases that latest, wrong, tag.

**To Reproduce**

My lib's latest release is `4.2.2`, and the last pushed tag (through lerna) is 4.2.3, and running the command `auto release --dry-run` gives:
```
Would have released (unless ran with "shipit"): v5.1.2
```
Which is a random version that doesn't appear anywhere in the codebase or release history.

**Expected behavior**

Should release `4.2.3` as per the last pushed tag. (unless im misunderstanding the behaviour of `auto release`?

**Screenshots**

![image](https://user-images.githubusercontent.com/16778318/67071073-ea91a700-f181-11e9-8ad1-513ee7eccb47.png)

**Desktop (please complete the following information):**

- OS: Mac OS 10.14.6
- Browser: Chrome
- Version: 77

**Additional context**
Here is the releases page on github for the repo:
![image](https://user-images.githubusercontent.com/16778318/66383955-2b3d3380-e9be-11e9-8e8b-dc2ef60040a9.png)

Here are the logs from the dry run with the `--verbose`, if it can give some insight.
[Terminal.Saved.Output.txt](https://github.com/intuit/auto/files/3742529/Terminal.Saved.Output.txt)

**Comment by vibu267** [comment] 2019-10-16 13:24
Hello, i would like to pick this up

**Comment by hipstersmoothie** [comment] 2019-10-16 15:34
@vibu267 if you can fix it I'll merge your pr!

**Comment by hipstersmoothie** [comment] 2019-10-17 16:06
@nicmosc is there any chance I could get access to this repo? 

Side note: just noticed that you put a token in your screenshot. You might want to invalidate that token. I'll remove the image for you.

**Comment by hipstersmoothie** [comment] 2019-10-17 18:58
if you could just give me access to the repo I can play around with it. you shouldn't have to make it public.

**Comment by hipstersmoothie** [comment] 2019-11-28 22:34
Since there has been no progress on being able to reproduce this I am closing. If you can come up with any new info feel free to open another issue! We could even pair program it

**Closed by hipstersmoothie** 2019-11-28 22:34 UTC
Labels: bug
